imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en
    be_simple.sso_auth.client.option.curlopt_sslversion.value: 0

services:
    fos_user.doctrine_registry:
        alias: doctrine

sensio_framework_extra:
  router:
    annotations: false

framework:
    #esi:             ~
    translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_hosts:   ~
    session:
        # http://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id:  session.handler.native_file
        save_path:   "%kernel.root_dir%/../var/sessions/%kernel.environment%"

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    form_themes:
        - '@FOSCKEditor/Form/ckeditor_widget.html.twig'

# Doctrine Configuration
doctrine:
    dbal:
        driver:   pdo_mysql
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #     path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

# Doctrine extensions
stof_doctrine_extensions:
  default_locale: en_US
  orm:
    default:
      timestampable: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    port:      "%mailer_port%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    encryption:  "%mailer_encryption%"
    spool:     { type: memory }

be_simple_sso_auth:
    admin_sso:
        protocol:
            id: cas
            version: 2
        server:
            id: cas
            login_url: https://cas.uga.edu/cas/login
            logout_url: https://cas.uga.edu/cas/logout
            validation_url: https://cas.uga.edu/cas/serviceValidate

fos_user:
    db_driver: orm # other valid values are 'mongodb', 'couchdb' and 'propel'
    firewall_name: main
    user_class: AppBundle\Entity\User
    registration:
        form:
            type: cert_user_registration
        confirmation:
            enabled:    false
    from_email:
        address:        scdirector@uga.edu
        sender_name:    "Sustainability Certificate"

vich_uploader:
    db_driver: orm

    mappings:
        upload:
            uri_prefix:         "%kernel.root_dir%/../uploads"
            upload_destination: "%kernel.root_dir%/../uploads"
            delete_on_remove: true # determines whether to delete file upon removal of entity
            inject_on_load: true # determines whether to inject a File instance upon load



fos_ck_editor:
    configs:
        editor_default:
            toolbar: "toolbar_default"
            removePlugins: "elementspath,contextmenu,liststyle,tabletools"
            allowedContent: 'p h2 h3 h4 img{text-align,margin-left}(*); a[!href,target]{*}(*); table th tr td strong em; ol ul li span(*){font-size,font-family,color,background-color}; img[*]{*}; iframe{*}[*];'
            disableNativeSpellChecker: false
            height: 300
            stylesSet: 'cert_styles:../../bundles/app/js/ckeditor_styles.js'
        editor_simple:
            toolbar: "toolbar_simple"
            removePlugins: "elementspath,contextmenu,liststyle,tabletools"
            allowedContent: 'p h2 h3 h4 img{text-align,margin-left}(*); a[!href,target]{*}(*); table th tr td strong em; ol ul li span(*); img[*]{*}; iframe{*}[*];'
            disableNativeSpellChecker: false
            height: 150
        editor_page:
            startupFocus: true
            toolbar: "toolbar_page"
            removePlugins: "elementspath,contextmenu,liststyle,tabletools"
            allowedContent: 'p h2 h3 h4 img{text-align,margin-left}(*); a[*]{*}(*);div[*]{*}(*);button[*]{*}(*); table th tr td strong em; ol ul li span(*){font-size,font-family,color,background-color}; img[*]{*}; iframe{*}[*];'
            disableNativeSpellChecker: false
            height: 500
            stylesSet: 'cert_styles:../../bundles/app/js/ckeditor_styles.js'
    toolbars:
        configs:
            toolbar_default: [ ['Styles','Bold','Italic','Underline','Strike','JustifyLeft','JustifyCenter','JustifyRight','TextColor','BGColor','FontSize'],['Link','Unlink','NumberedList','BulletedList','Outdent','Indent','Image','MediaEmbed'],[ 'Undo', 'Redo','RemoveFormat'] ]
            toolbar_simple: [ ['Bold','Italic','Underline','Strike'],['Link','Unlink'],['NumberedList','BulletedList']]
            toolbar_page: [ ['Source','Styles','Bold','Italic','Underline','Strike','Font','FontSize'],['JustifyLeft','JustifyCenter','JustifyRight'],['TextColor','BGColor'],['Link','Unlink'],['NumberedList','BulletedList'],['Outdent','Indent'],['Image'],[ 'PasteText', 'Table', 'Undo', 'Redo','RemoveFormat','Maximize'] ]

