login:
    path: /login
    defaults: { _controller: AppBundle:Default:index}

logout:
    path: /logout
    defaults: { _controller: AppBundle:Default:index}

login_check:
    path: /login_check

alumni:
    path: /alumni
    defaults:
        _controller: FrameworkBundle:Redirect:urlRedirect
        path: /page/Alumni
        permanent: true

adesigns_calendar:
  resource: "@ADesignsCalendarBundle/Resources/config/routing.xml"

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

