login:
    path: /login
    defaults: { _controller: AppBundle:Default:index}

logout:
    path: /logout
    defaults: { _controller: AppBundle:Default:index}

login_check:
    path: /login_check

alumni:
    path: /alumni
    defaults:
        _controller: FrameworkBundle:Redirect:urlRedirect
        path: /page/Alumni
        permanent: true

apply:
    path: /apply
    defaults:
        _controller: FrameworkBundle:Redirect:urlRedirect
        path: /page/20/show
        permanent: true

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

