login:
    path: /login
    defaults: { _controller: AppBundle:Default:index}

logout:
    path: /logout
    defaults: { _controller: AppBundle:Default:index}

login_check:
    path: /login_check

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"