security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
        ROLE_UNIT:       ROLE_USER, ROLE_INSTRUCTOR
        ROLE_ADMIN:       ROLE_USER, ROLE_UNIT, ROLE_INSTRUCTOR
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_provider: form.csrf_provider
                default_target_path: /
            logout:
                path:   /logout
                target: /login
            anonymous:    true

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
        - { path: edit$, role: ROLE_ADMIN }
        - { path: new$, role: ROLE_ADMIN }
        - { path: delete$, role: ROLE_ADMIN }
        - { path: create$, role: ROLE_ADMIN }
        - { path: update$, role: ROLE_ADMIN }
        - { path: ^/course/, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/page/, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/upload/, role: ROLE_ADMIN }
