<?php

namespace AppBundle\Entity;

/**
 * CapstoneRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CapstoneRepository extends \Doctrine\ORM\EntityRepository
{
}
