<?php

namespace AppBundle\Entity;

/**
 * CapstoneRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CapstoneRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * Find users by type
     *
     * @return User
     */
    public function findByType($type)
    {
        if ($type == 'Peer') {
            $status = 'Ready for Peer Review';
        }
        else {
            $status = 'Ready for Director Review';
        }

        $course = $this->createQueryBuilder('c')
            ->andWhere("c.status = :type")
            ->setParameter('type', $status)
            ->getQuery()
            ->getResult();
        return $course;
    }
}
