<?php

namespace AppBundle\Entity;

/**
 * CourseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CourseRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * find course by pillar
     *
     * @return Course
     */
    public function findByPillar($pillar) {
        $courses = $this->createQueryBuilder('c')
            ->andWhere('c.pillar = :pillar')
            ->setParameter('pillar', $pillar)
            ->orderBy('c.name ')
            ->getQuery()
            ->getResult();
        return $courses;
    }
}
