<?php

namespace AppBundle\Entity;

/**
 * CourseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CourseRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * find course by pillar
     *
     * @return Course
     */
    public function findByPillar($pillar, $level) {
        $courses = $this->createQueryBuilder('c')
            ->andWhere('c.pillar = :pillar')
            ->andWhere('c.level = :level')
            ->setParameter('pillar', $pillar)
            ->setParameter('level', $level)
            ->orderBy('c.name ')
            ->getQuery()
            ->getResult();
        return $courses;
    }
}
