<?php

namespace AppBundle\Entity;

/**
 * EventRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EventRepository extends \Doctrine\ORM\EntityRepository
{

    /**
     * Find all upcoming events sorted by start
     *
     * @return Event
     */
    public function findCurrent() {
        $today = date("Y-m-d");
        $events = $this->createQueryBuilder('e')
          ->andWhere('e.datetime >= :today')
          ->orderBy('e.datetime', 'ASC')
          ->setParameter('today',$today)
          ->getQuery()
          ->getResult();
        return $events;
    }
}
