<?php

namespace AppBundle\Entity;

/**
 * ExceptionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ExceptionRepository extends \Doctrine\ORM\EntityRepository
{
}
