<?php

namespace AppBundle\Entity;

/**
 * FeatureRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FeatureRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * find feature sorted by position
     *
     * @return Feature
     */
    public function findAllSorted() {
        $features = $this->createQueryBuilder('f')
            ->orderBy('f.position')
            ->getQuery()
            ->getResult();
        return $features;
    }
}
