<?php

namespace AppBundle\Entity;

/**
 * ForumRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ForumRepository extends \Doctrine\ORM\EntityRepository
{

    /**
     * find forum entities with no parent
     *
     * @return Forum
     */
    public function findTopLevel() {
        $forums = $this->createQueryBuilder('f')
            ->andWhere('f.parent is NULL')
            ->orderBy('f.title')
            ->getQuery()
            ->getResult();
        return $forums;
    }

    /**
     * find forum entities with no parent
     *
     * @return Forum
     */
    public function findNetwork() {
        $forums = $this->createQueryBuilder('f')
            ->andWhere('f.parent is NULL and f.network=0')
            ->orderBy('f.title')
            ->getQuery()
            ->getResult();
        return $forums;
    }

}
