<?php

namespace AppBundle\Entity;

/**
 * NotificationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NotificationRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * find current notifications
     *
     * @return Notification
     */
    public function findCurrent($user) {
        $notifications = $this->createQueryBuilder('n')
            ->andWhere('n.status != :status')
            ->andWhere('n.user = :user')
            ->setParameter('status', 'Dismissed')
            ->setParameter('user', $user)
            ->getQuery()
            ->getResult();
        return $notifications;
    }
}
