<?php

namespace AppBundle\Entity;

/**
 * NotificationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NotificationRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * find current notifications
     *
     * @return Notification
     */
    public function findCurrent($user) {
        $now = date_create();
        $notifications = $this->createQueryBuilder('n')
            ->andWhere('n.display_start < :now')
            ->andWhere('n.display_end > :now')
            ->andWhere('n.status != :status')
            ->andWhere('n.user = :user or n.status = :status2')
            ->setParameter('status', 'Dismissed')
            ->setParameter('user', $user)
            ->setParameter('status2', 'Shared')
            ->setParameter('now', $now)
            ->getQuery()
            ->getResult();
        return $notifications;
    }
}
