<?php

namespace AppBundle\Entity;

/**
 * PageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PageRepository extends \Doctrine\ORM\EntityRepository
{
	
	/**
* find newsletter by sortorder
*
* @return Course
*/
public function findCurrent() {
	$page = $this->createQueryBuilder('p')
		->join('p.section', 's')
		->andWhere('s.title = :title')
		->setParameter('title', 'News')
		->orderBy('p.sortorder')
		->setMaxResults(1)
		->getQuery()
		->getSingleResult();
	return $page;
}



    /**
     * find page by section
     *
     * @return Page
     */
    public function findPageBySection($section) {
        $page = $this->createQueryBuilder('p')
            ->join('p.section', 's')
            ->andWhere('s.title = :title')
            ->setParameter('title', $section)
            ->orderBy('p.sortorder')
            ->setMaxResults(1)
            ->getQuery()
            ->getSingleResult();
        return $page;
    }


}
