<?php

namespace AppBundle\Entity;

/**
 * PartnerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PartnerRepository extends \Doctrine\ORM\EntityRepository
{
}
