<?php

namespace AppBundle\Entity;

/**
 * QuestionsetRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class QuestionsetRepository extends \Doctrine\ORM\EntityRepository
{
}
