<?php

namespace AppBundle\Entity;

/**
 * QuestionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class QuestionRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * find default answerset for text question creation
     *
     * @return Question
     */
    public function findQuestions($type) {

        $questions = $this->createQueryBuilder('q')
            ->join('q.questionset','s')
            ->andWhere('s.title = :type')
            ->setParameter('type', $type)
            ->getQuery()
            ->getResult();
        return $questions;
    }
}
