<?php

namespace AppBundle\Entity;

/**
 * ResponsesetRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ResponsesetRepository extends \Doctrine\ORM\EntityRepository
{
}
