<?php

namespace AppBundle\Entity;

/**
 * SchoolRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SchoolRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * find schools data
     *
     */
    public function findSchoolData() {
        $data = $this->createQueryBuilder('s')
            ->join('s.program1', 'pr')
            ->join('pr.user', 'u')
            ->join('u.progress', 'p')
            ->andWhere(':tag MEMBER OF u.tags')
            ->select('s.name AS area', 'count(s.id) AS value')
            ->groupBy('s.name')
            ->orderBy("value", "DESC")
            ->setParameter('tag', 116)
            ->getQuery()
            ->getResult();
        return $data;
    }

}
