<?php

namespace AppBundle\Entity;

/**
 * SchoolRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SchoolRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * find schools data
     *
     */
    public function findSchoolData() {
        $data = $this->createQueryBuilder('s')
            ->join('s.program1', 'p')
            ->join('p.user', 'u')
            ->select('s.name AS area', 'count(s.id) AS value')
            ->andWhere("p.status!='Inactive'")
            ->orWhere("p.status!='Graduated'")
            ->orWhere("p.status!='Administration'")
            ->groupBy('s.id')
            ->orderBy("value", "DESC")
            ->getQuery()
            ->getResult();
        return $data;
    }

}
