<?php

namespace AppBundle\Entity;

/**
 * SourceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SourceRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * Find sources
     *
     * @return Source
     */
    public function findSourcesSorted()
    {
        $sources = $this->createQueryBuilder('s')
            ->addOrderBy('s.type', 'DESC')
            ->getQuery()
            ->getResult();
        return $sources;
    }
}
