<?php

namespace AppBundle\Entity;

/**
 * SourceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SourceRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * Find sources
     *
     * @return Source
     */
    public function findSourcesSorted()
    {
        $sources = $this->createQueryBuilder('s')
            ->addOrderBy('s.type', 'DESC')
            ->getQuery()
            ->getResult();
        return $sources;
    }

    /**
     * Find sources
     *
     * @return Source
     */
    public function findContentSorted()
    {
        $sources = $this->createQueryBuilder('s')
            ->join('s.tags', 't')
            ->andWhere("t.type = :type")
            ->setParameter('type', 'content')
            ->addOrderBy('s.name', 'DESC')
            ->getQuery()
            ->getResult();
        return $sources;
    }

    /**
     * Find users by term
     *
     * @return User
     */
    public function findSourcesByIdea($id)
    {
        $course = $this->createQueryBuilder('s')
            ->join('s.tags', 't')
            ->join('t.ideas', 'i')
            ->andWhere("i.id = :idea")
            ->setParameter('idea', $id)
            ->getQuery()
            ->getResult();
        return $course;
    }
}
