<?php

namespace AppBundle\Entity;

/**
 * SubstitutionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SubstitutionRepository extends \Doctrine\ORM\EntityRepository
{
}
