<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UploadRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UploadRepository extends EntityRepository
{
    /**
     * Find all uploaded ics files
     *
     * @return Upload
     */
    public function findIcsSources() {
        $ics_sources = $this->createQueryBuilder('u')
            ->andWhere('u.type = :type')
            ->setParameter('type','iCal')
            ->getQuery()
            ->getResult();
        return $ics_sources;
    }
}
