<?php

namespace AppBundle\Entity;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{

    /**
     * Find users by type
     *
     * @return User
     */
    public function findUsersByType($type)
    {
        $course = $this->createQueryBuilder('u')
            ->andWhere("u.progress = :type")
            ->setParameter('type', $type)
            ->getQuery()
            ->getResult();
        return $course;
    }

    /**
     * Find student users
     *
     * @return User
     */
    public function findStudents()
    {
        $course = $this->createQueryBuilder('u')
            ->join('u.progress', 'p')
            ->andWhere("p.name != 'Administration' and p.name != 'Faculty' and p.name != 'Graduated'  and p.name != 'Account Created'")
            ->getQuery()
            ->getResult();
        return $course;
    }

}
